### PR TITLE
Without this fix the container restarts after every login over ssh

### PR DESCRIPTION
**Pull request by ripienaar**

### CODE REVIEW

**Comment by codeskyblue** [comment]
Yes, but I don't know why?

**Comment by ripienaar** [comment]
Not sure couldn't get useful logs out of docker. I think priv sep must trigger a bug in it

Don't think it's a big deal to turn this off.

**Comment by ripienaar** [comment]
any chance we can get this one merged and a rebuild done?

**Comment by codeskyblue** [comment]
sorry, See it laterly.

**Pull request merged**
